spring:
    datasource:
        url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
        username: root
        password: mysql

    #The SQL Dialect makes Hibernate generate better SQL for the chosen Database
    # jpa:
    #     properties:
    #         hibernate:
    #             dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    #JPA Settings
    jpa.hibernate.ddl-auto: create  